/*
 * ThinkingRock, a project management tool for Personal Computers.
 * Copyright (C) 2006 Avente Pty Ltd
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package au.com.trgtd.tr.view.reference.screen;

import au.com.trgtd.tr.resource.Icons;
import au.com.trgtd.tr.appl.Constants;
import au.com.trgtd.tr.prefs.ui.GUIPrefs;
import ca.odell.glazedlists.matchers.MatcherEditor;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import org.openide.awt.Toolbar;
import java.io.Serializable;
import java.util.Collection;
import java.util.Collections;
import java.util.prefs.Preferences;
import javax.swing.AbstractAction;
import javax.swing.AbstractButton;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import javax.swing.JToolBar;
import org.openide.ErrorManager;
import org.openide.util.HelpCtx;
import org.openide.util.Lookup;
import org.openide.util.NbBundle;
import org.openide.util.actions.SystemAction;
import org.openide.util.lookup.AbstractLookup;
import org.openide.util.lookup.InstanceContent;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
import tr.model.information.Information;
import au.com.trgtd.tr.view.Window;
import au.com.trgtd.tr.view.reference.ReferenceAddAction;
import au.com.trgtd.tr.view.reference.ReferenceDeleteAction;
import au.com.trgtd.tr.view.reference.ReferenceEditAction;
import au.com.trgtd.tr.view.reference.ReferenceReprocessAction;

/**
 * Top component for the referenced information table.
 *
 * @author Jeremy Moore
 */
public final class ReferencesTopComponent extends Window implements ReferenceNodeProvider {
    
    public static final String PREFERRED_ID = "ReferencesTopComponent";
    
    private static final long serialVersionUID = 1L;
    
    private static final Preferences PREFS = Constants.getPrefs("references");   
    
    private static final String PREFS_KEY_SHOW_FILTERS = "show.filters";
    private static final boolean PREFS_DEF_SHOW_FILTERS = true;
    
    private static ReferencesTopComponent instance;
    
    private ReferencesPanel.Preferences panelPrefs;
    
    private transient ReferencesFilters filters;
    private transient ReferencesPanel panel;
    private transient InstanceContent content;
    private transient Lookup lookup;
    private transient JToolBar toolbar;
    private transient JPanel bodyPanel;
    private transient JToggleButton filtersButton;
    
    /* Singleton instance. */
    private ReferencesTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(ReferencesTopComponent.class, "CTL_ReferencesTopComponent"));
        setToolTipText(NbBundle.getMessage(ReferencesTopComponent.class, "TTT_ReferencesTopComponent"));
        setIcon(Icons.References.getImage());            
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());

    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link findInstance}.
     * @return 
     */
    public static synchronized ReferencesTopComponent getDefault() {
        if (instance == null) {
            instance = new ReferencesTopComponent();
        }
        return instance;
    }
    
    /**
     * Obtain the CollectTopComponent instance. Never call {@link #getDefault}
     * directly!
     * @return 
     */
    public static synchronized ReferencesTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            ErrorManager.getDefault().log(ErrorManager.WARNING, "Cannot find collect thoughts component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof ReferencesTopComponent comp) {
            return comp;
        }
        ErrorManager.getDefault().log(ErrorManager.WARNING, "There seem to be multiple components with the '" + PREFERRED_ID + "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }
    
    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }
    
    private JToolBar getToolBar() {
        if (toolbar == null) {
            SystemAction[] actions = new SystemAction[] {
                SystemAction.get(ReferenceAddAction.class),
                SystemAction.get(ReferenceEditAction.class),
                SystemAction.get(ReferenceDeleteAction.class),
                SystemAction.get(ReferenceReprocessAction.class)
            };
            toolbar = SystemAction.createToolbarPresenter(actions);
            filtersButton = new JToggleButton(new FiltersAction());
            toolbar.add(filtersButton, 0);
            toolbar.setUI((new Toolbar()).getUI());
            toolbar.setFloatable(false);
            
            Dimension buttonSize = Constants.TOOLBAR_BUTTON_SIZE;
            for (Component component : toolbar.getComponents()) {
                if (component instanceof AbstractButton) {
                    component.setPreferredSize(buttonSize);
                    component.setMinimumSize(buttonSize);
                    component.setMaximumSize(buttonSize);
                    component.setSize(buttonSize);
                }
            }
        }
        return toolbar;
    }
    
    private class FiltersAction extends AbstractAction {
        public FiltersAction() {
            super("", Icons.FiltersView);
            putValue(SHORT_DESCRIPTION, NbBundle.getMessage(getClass(), "CTL_FiltersAction"));
        }
        @Override
        public void actionPerformed(ActionEvent e) {
            if (filtersButton.isSelected()) {
                bodyPanel.add(getFilters().getComponent(), BorderLayout.NORTH);
            } else {
                bodyPanel.remove(getFilters().getComponent());
            }
            validate();
        }
    }
    
    private ReferencesFilters getFilters() {
        if (filters == null) {
            filters = new ReferencesFilters();
        }
        return filters;
    }
    
    private MatcherEditor<Information> getMatcherEditor() {
        return getFilters().getMatcherEditor();
    }
    
    @Override
    protected void componentOpened() {
        super.componentOpened();
        
        provide(null);
        
        removeAll();
        
        getToolBar();
//      filtersButton.setSelected(false);
        
        String position = GUIPrefs.getButtonsPosition();
        if (position.equals(GUIPrefs.BUTTONS_POSITION_TOP)) {
            toolbar.setOrientation(JToolBar.HORIZONTAL);
            add(toolbar, BorderLayout.NORTH);
        } else if (position.equals(GUIPrefs.BUTTONS_POSITION_BOTTOM)) {
            toolbar.setOrientation(JToolBar.HORIZONTAL);
            add(toolbar, BorderLayout.SOUTH);
        } else if (position.equals(GUIPrefs.BUTTONS_POSITION_LEFT)) {
            toolbar.setOrientation(JToolBar.VERTICAL);
            add(toolbar, BorderLayout.WEST);
        } else if (position.equals(GUIPrefs.BUTTONS_POSITION_RIGHT)) {
            toolbar.setOrientation(JToolBar.VERTICAL);
            add(toolbar, BorderLayout.EAST);
        }
        
        panel = new ReferencesPanel(this, getMatcherEditor());
        panel.setPreferences(panelPrefs);
        
        bodyPanel = new JPanel(new BorderLayout());
        bodyPanel.add(panel, BorderLayout.CENTER);
        
        add(bodyPanel, BorderLayout.CENTER);
        
        // restore showFilters from preference
        boolean b = PREFS.getBoolean(PREFS_KEY_SHOW_FILTERS, PREFS_DEF_SHOW_FILTERS);
        filtersButton.setSelected(b);
        filtersButton.getAction().actionPerformed(null);
    }
    
    @Override
    protected void componentClosed() {
        panelPrefs = panel.getPreferences();
        
        // save show filters as a preference
        PREFS.putBoolean(PREFS_KEY_SHOW_FILTERS, filtersButton.isSelected());
        
        super.componentClosed();
    }
    
    private synchronized InstanceContent getInstanceContent() {
        if (content == null) {
            content = new InstanceContent();
        }
        return content;
    }
    
    @Override
    public Lookup getLookup() {
        if (lookup == null) {
            lookup = new AbstractLookup(getInstanceContent());
        }
        return lookup;
    }
    
    public void provide(final Collection<ReferenceNode> nodes) {
        EventQueue.invokeLater(() -> {
            if (panel == null || nodes == null) {
                getInstanceContent().set(Collections.EMPTY_LIST, null);
            } else {
                getInstanceContent().set(nodes, null);
            }
        });
    }

    public void select(Information reference) {
        filters.reset();
        panel.select(reference);
    }
    
    @Override
    public HelpCtx getHelpCtx() {
        return new HelpCtx("tr.view.reference");
    }
    
    @Override
    public String preferredID() {
        return PREFERRED_ID;
    }
    
    /** replaces this in object stream */
    @Override
    public Object writeReplace() {
        return new ResolvableHelper(panel.getPreferences(), getFilters().getSerializable());
    }
    
    final static class ResolvableHelper implements Serializable {
        private static final long serialVersionUID = 1L;
        
        private final ReferencesPanel.Preferences prefs;
        private final Serializable rmes;
        
        public ResolvableHelper(ReferencesPanel.Preferences prefs, Serializable rmes) {
            this.prefs = prefs;
            this.rmes = rmes;
        }
        
        public Object readResolve() {
            ReferencesTopComponent result = ReferencesTopComponent.getDefault();
            result.panelPrefs = prefs;
            result.filters = new ReferencesFilters();
            result.filters.setSerializable(rmes);
            return result;
        }
    }
    
}
