/*
 * The contents of this file are subject to the terms of the Common Development
 * and Distribution License (the License). You may not use this file except in
 * compliance with the License.
 *
 * You can get a copy of the License at http://www.thinkingrock.com.au/cddl.html
 * or http://www.thinkingrock.com.au/cddl.txt.
 *
 * When distributing Covered Code, include this CDDL Header Notice in each file
 * and include the License file at http://www.thinkingrock.com.au/cddl.txt.
 * If applicable, add the following below the CDDL Header, with the fields
 * enclosed by brackets [] replaced by your own identifying information:
 * "Portions Copyright [year] [name of copyright owner]"
 * 
 * The Original Software is ThinkingRock. The Initial Developer of the Original
 * Software is Avente Pty Ltd, Australia.
 *
 * Portions Copyright 2006-2007 Avente Pty Ltd. All Rights Reserved.
 */
package au.com.trgtd.tr.view.topics.dialog;

import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JPanel;
import org.openide.util.NbBundle;

/**
 * Topic panel.
 *
 * @author Jeremy Moore
 */
public class TopicDialogPanel extends JPanel {
    
    /** Constructs a new instance. */
    public TopicDialogPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        descLabel = new javax.swing.JLabel();
        descTextField = new javax.swing.JTextField();
        fgColourLabel = new javax.swing.JLabel();
        fgColourButton = new javax.swing.JButton();
        bgColourLabel = new javax.swing.JLabel();
        bgColourButton = new javax.swing.JButton();

        nameLabel.setBackground(javax.swing.UIManager.getDefaults().getColor("Nb.ScrollPane.Border.color"));
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        nameLabel.setText(org.openide.util.NbBundle.getMessage(TopicDialogPanel.class, "name")); // NOI18N

        descLabel.setBackground(javax.swing.UIManager.getDefaults().getColor("Nb.ScrollPane.Border.color"));
        descLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        descLabel.setText(NbBundle.getMessage(TopicDialogPanel.class, "description")); // NOI18N

        fgColourLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fgColourLabel.setText(NbBundle.getMessage(TopicDialogPanel.class, "colour.text")); // NOI18N

        fgColourButton.setText(NbBundle.getMessage(TopicDialogPanel.class, "colour.choose")); // NOI18N
        fgColourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textColourActionPerformed(evt);
            }
        });

        bgColourLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bgColourLabel.setText(NbBundle.getMessage(TopicDialogPanel.class, "colour.back")); // NOI18N

        bgColourButton.setText(NbBundle.getMessage(TopicDialogPanel.class, "colour.choose")); // NOI18N
        bgColourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgColourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(descLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(fgColourLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fgColourButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bgColourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bgColourButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descLabel)
                    .addComponent(descTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fgColourButton)
                    .addComponent(fgColourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bgColourLabel)
                    .addComponent(bgColourButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void bgColourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgColourActionPerformed
        Color c = JColorChooser.showDialog(TopicDialogPanel.this, org.openide.util.NbBundle.getMessage(TopicDialogPanel.class, "choose.background.colour"), getBgColor());
        if (c != null) {
            setBgColor(c);            
        }
    }//GEN-LAST:event_bgColourActionPerformed
    
    private void textColourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textColourActionPerformed
        Color c = JColorChooser.showDialog(TopicDialogPanel.this, org.openide.util.NbBundle.getMessage(TopicDialogPanel.class, "choose.text.colour"), getFgColor());        
        if (c != null) {
            setFgColor(c);
        }        
    }//GEN-LAST:event_textColourActionPerformed
    
    public void setTopicName(String name) {
        nameTextField.setText(name);
    }
    
    public String getTopicName() {
        return nameTextField.getText();
    }
    
    public void setDescription(String desc) {
        descTextField.setText(desc);
    }
    
    public String getDescription() {
        return descTextField.getText();
    }
    
    public void focus() {
        requestFocusInWindow();
        nameTextField.requestFocusInWindow();
    }
    
    public Color getFgColor() {
        return fgColor;
    }
    
    public void setFgColor(Color fgColor) {
        this.fgColor = (fgColor == null) ? Color.BLACK : fgColor;
        nameTextField.setForeground(fgColor);
        descTextField.setForeground(fgColor);
    }
    
    public Color getBgColor() {
        return bgColor;
    }
    
    public void setBgColor(Color bgColor) {
        this.bgColor = (bgColor == null) ? Color.BLACK : bgColor;
        nameTextField.setBackground(bgColor);
        descTextField.setBackground(bgColor);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bgColourButton;
    private javax.swing.JLabel bgColourLabel;
    private javax.swing.JLabel descLabel;
    private javax.swing.JTextField descTextField;
    private javax.swing.JButton fgColourButton;
    private javax.swing.JLabel fgColourLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    // End of variables declaration//GEN-END:variables
    
    private Color fgColor;
    private Color bgColor;
    
}
