/*
 * ThinkingRock, a project management tool for Personal Computers. 
 * Copyright (C) 2006 Avente Pty Ltd
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package au.com.trgtd.tr.view.topics.screen;

import au.com.trgtd.tr.resource.Icons;
import au.com.trgtd.tr.appl.Constants;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.io.Serializable;
import java.util.Collection;
import java.util.Collections;
import javax.swing.AbstractButton;
import javax.swing.JToolBar;
import org.openide.ErrorManager;
import org.openide.awt.Toolbar;
import org.openide.util.HelpCtx;
import org.openide.util.Lookup;
import org.openide.util.NbBundle;
import org.openide.util.actions.SystemAction;
import org.openide.util.lookup.AbstractLookup;
import org.openide.util.lookup.InstanceContent;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
import au.com.trgtd.tr.prefs.ui.GUIPrefs;
import au.com.trgtd.tr.view.Window;
import au.com.trgtd.tr.view.topics.AddTopicsAction;
import au.com.trgtd.tr.view.topics.DeleteTopicAction;
import au.com.trgtd.tr.view.topics.EditTopicAction;

/**
 * Top component for the topics window.
 *
 * @author Jeremy Moore
 */
public final class TopicsTopComponent extends Window implements TopicNodeProvider {
    
    private static final long serialVersionUID = 1L;
    
    private static final String PREFERRED_ID = "TopicsTopComponent";
    
    private static TopicsTopComponent instance;
    
    private TopicsPanel.Preferences panelPrefs;
    private TopicsPanel panel;
    private InstanceContent content;
    private Lookup lookup;
    private JToolBar toolbar;
    
    /* Singleton instance. */
    private TopicsTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(TopicsTopComponent.class, "CTL_TopicsTopComponent"));
        setToolTipText(NbBundle.getMessage(TopicsTopComponent.class, "TTT_TopicsTopComponent"));
        setIcon(Icons.Topics.getImage());            
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());

    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link findInstance}.
     */
    public static synchronized TopicsTopComponent getDefault() {
        if (instance == null) {
            instance = new TopicsTopComponent();
        }
        return instance;
    }
    
    /**
     * Obtain the CollectTopComponent instance. Never call {@link #getDefault}
     * directly!
     */
    public static synchronized TopicsTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            ErrorManager.getDefault().log(ErrorManager.WARNING, "Cannot find topics component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof TopicsTopComponent topicsTopComponent) {
            return topicsTopComponent;
        }
        ErrorManager.getDefault().log(ErrorManager.WARNING, "There seem to be multiple components with the '" + PREFERRED_ID + "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }
    
    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }
    
    private JToolBar getToolBar() {
        if (toolbar == null) {
            SystemAction[] actions = new SystemAction[] {
                SystemAction.get(AddTopicsAction.class),
//              null,
                SystemAction.get(EditTopicAction.class),
//              null,
                SystemAction.get(DeleteTopicAction.class)
            };
            toolbar = SystemAction.createToolbarPresenter(actions);
            toolbar.setUI((new Toolbar()).getUI());
            toolbar.setFloatable(false);
            
            Dimension buttonSize = Constants.TOOLBAR_BUTTON_SIZE;
            for (Component component : toolbar.getComponents()) {
                if (component instanceof AbstractButton) {
                    component.setPreferredSize(buttonSize);
                    component.setMinimumSize(buttonSize);
                    component.setMaximumSize(buttonSize);
                    component.setSize(buttonSize);
                }
            }
        }
        return toolbar;
    }
    
    @Override
    protected void componentOpened() {
        super.componentOpened();
        
        provide(null);
        
        removeAll();
        
        JToolBar tb = getToolBar();
        String position = GUIPrefs.getButtonsPosition();
        if (position.equals(GUIPrefs.BUTTONS_POSITION_TOP)) {
            tb.setOrientation(JToolBar.HORIZONTAL);
            add(getToolBar(), BorderLayout.NORTH);
        } else if (position.equals(GUIPrefs.BUTTONS_POSITION_BOTTOM)) {
            tb.setOrientation(JToolBar.HORIZONTAL);
            add(getToolBar(), BorderLayout.SOUTH);
        } else if (position.equals(GUIPrefs.BUTTONS_POSITION_LEFT)) {
            tb.setOrientation(JToolBar.VERTICAL);
            add(getToolBar(), BorderLayout.WEST);
        } else if (position.equals(GUIPrefs.BUTTONS_POSITION_RIGHT)) {
            tb.setOrientation(JToolBar.VERTICAL);
            add(getToolBar(), BorderLayout.EAST);
        }
        
        panel = new TopicsPanel(this);
        panel.setPreferences(panelPrefs);
        
        add(panel, BorderLayout.CENTER);
    }
    
    @Override
    protected void componentClosed() {
        panelPrefs = panel.getPreferences();
        
        super.componentClosed();
    }
    
    private synchronized InstanceContent getInstanceContent() {
        if (content == null) {
            content = new InstanceContent();
        }
        return content;
    }
    
    @Override
    public Lookup getLookup() {
        if (lookup == null) {
            lookup = new AbstractLookup(getInstanceContent());
        }
        return lookup;
    }
    
    public void provide(final Collection<TopicNode> topicNodes) {
        EventQueue.invokeLater(() -> {
            if (panel == null || topicNodes == null) {
                getInstanceContent().set(Collections.EMPTY_LIST, null);
            } else {
                getInstanceContent().set(topicNodes, null);
            }
        });
    }
    
    @Override
    public HelpCtx getHelpCtx() {
        return new HelpCtx("tr.view.topics");
    }
    
    @Override
    public String preferredID() {
        return PREFERRED_ID;
    }
    
    /** replaces this in object stream */
    @Override
    public Object writeReplace() {
        return new ResolvableHelper(panel.getPreferences());
    }
    
    final static class ResolvableHelper implements Serializable {
        private static final long serialVersionUID = 1L;
        
        private final TopicsPanel.Preferences prefs;
        
        public ResolvableHelper(TopicsPanel.Preferences prefs) {
            this.prefs = prefs;
        }
        
        public Object readResolve() {
            TopicsTopComponent result = TopicsTopComponent.getDefault();
            result.panelPrefs = prefs;
            return result;
        }
    }
    
}
