//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2008.02.14 at 10:19:02 AM EST
//
package au.com.thinkingrock.xsd.tr.view.actions.screens;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Filter complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Filter">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="filterID" type="{http://thinkingrock.com.au/xsd/tr/view/actions/screens}FilterID" />
 *       &lt;attribute name="visible" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Filter", propOrder = {
    "value"
})
public class Filter {
    
    protected List<String> value;
    @XmlAttribute
    protected FilterID filterID;
    @XmlAttribute
    protected Boolean visible;
    @XmlAttribute
    protected Boolean excludeNulls;
    
    /**
     * Gets the value of the value property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the value property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValue().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     *
     *
     */
    public List<String> getValues() {
        if (value == null) {
            value = new ArrayList<>();
        }
        return this.value;
    }
    
    /**
     * Gets the value of the filterID property.
     *
     * @return
     *     possible object is
     *     {@link FilterID }
     *
     */
    public FilterID getFilterID() {
        return filterID;
    }
    
    /**
     * Sets the value of the filterID property.
     *
     * @param value
     *     allowed object is
     *     {@link FilterID }
     *
     */
    public void setFilterID(FilterID value) {
        this.filterID = value;
    }
    
    /**
     * Gets the value of the visible property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isVisible() {
        return visible == null ? true : visible;
    }
    
    /**
     * Sets the value of the visible property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setVisible(Boolean value) {
        this.visible = value;
    }
    
    /**
     * Gets the value of the exclude nulls property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isExcludeNulls() {
        return excludeNulls == null ? false : excludeNulls;
    }
    
    /**
     * Sets the value of the exclude nulls property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setExcludeNulls(Boolean value) {
        this.excludeNulls = value;
    }
    
}
