//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.14 at 10:19:02 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://thinkingrock.com.au/xsd/tr/view/actions/screens", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package au.com.thinkingrock.xsd.tr.view.actions.screens;
