//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2008.03.06 at 09:14:48 AM EST
//
package au.com.thinkingrock.xsd.tr.view.actions.screens;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Screen complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Screen">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://thinkingrock.com.au/xsd/tr/view/actions/screens}columns"/>
 *         &lt;element ref="{http://thinkingrock.com.au/xsd/tr/view/actions/screens}sortColumns"/>
 *         &lt;element ref="{http://thinkingrock.com.au/xsd/tr/view/actions/screens}filters"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Screen", propOrder = {
    "columns",
    "sortColumns",
    "filters"
})
public class Screen {
    
    @XmlElement(required = true)
    protected Columns columns;
    @XmlElement(required = true)
    protected SortColumns sortColumns;
    @XmlElement(required = true)
    protected Filters filters;
    @XmlAttribute
    protected String name;
    
    
    public Screen() {
    }
    
    public Screen(String name) {
        this.setName(name);
    }
    
    
    /**
     * Gets the value of the columns property.
     *
     * @return
     *     possible object is
     *     {@link Columns }
     *
     */
    public Columns getColumns() {
        if (columns == null) {
            columns = new Columns();
        }
        return columns;
    }
    
    /**
     * Sets the value of the columns property.
     *
     * @param value
     *     allowed object is
     *     {@link Columns }
     *
     */
    public void setColumns(Columns value) {
        this.columns = value;
    }
    
    /**
     * Gets the value of the sortColumns property.
     *
     * @return
     *     possible object is
     *     {@link SortColumns }
     *
     */
    public SortColumns getSortColumns() {
        if (sortColumns == null) {
            sortColumns = new SortColumns();
        }
        return sortColumns;
    }
    
    /**
     * Sets the value of the sortColumns property.
     *
     * @param value
     *     allowed object is
     *     {@link SortColumns }
     *
     */
    public void setSortColumns(SortColumns value) {
        this.sortColumns = value;
    }
    
    /**
     * Gets the value of the filters property.
     *
     * @return
     *     possible object is
     *     {@link Filters }
     *
     */
    public Filters getFilters() {
        if (filters == null) {
            filters = new Filters();
        }
        return filters;
    }
    
    /**
     * Sets the value of the filters property.
     *
     * @param value
     *     allowed object is
     *     {@link Filters }
     *
     */
    public void setFilters(Filters value) {
        this.filters = value;
    }
    
    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name == null ? "" : name;
    }
    
    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }
    
}
